// Tests for the search-miss empty state ("No Rawk Found") — backlog #21.
//
// What this locks in:
//
//   1. A zero-result SEARCH shows an empty-state card with the required
//      "No Rawk Found" headline and a CTA into the Add-band flow. A
//      zero-result *filter* combination does NOT — the band may well be in
//      the tree and simply filtered out, so offering to add it would be
//      wrong.
//   2. The card is a DOM overlay inside .graph-stage, a sibling of
//      #graph-svg. It is NOT drawn into the SVG, because renderGraph()
//      wipes the graph group and early-returns the moment the filtered node
//      set is empty — an in-SVG empty state would be erased by the exact
//      render that needs to show it.
//   3. Mobile parity. The card is not inside .graph-overlay-top (which is
//      display:none under 900px) and no media query hides it, so phones get
//      the same CTA. This is the PR #42/#44/#45/#63 trap.
//   4. The CTA routes through openSignupPopover() — the one existing funnel
//      that shows the sign-up gate to anonymous visitors and the Add-band
//      form to signed-in ones. No parallel gate.
//   5. Cleanup: the stale "from your uploaded CSV" copy is gone, and the
//      redundant #graph-note-left / #graph-note-right empty-state surface
//      (inside the globally display:none .graph-shell-footer) is gone with
//      it, leaving #graph-empty-state as the single search-miss surface and
//      #graph-badge as the single active-filter readout.
//
// Static HTML/JS regex checks in the same style as
// mobile-toolbar-parity.test.mjs and welcome-nudge-and-edit-cleanup.test.mjs
// — no browser, no DOM. The point is catching structural regressions in CI.

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const INDEX_HTML = readFileSync(join(__dirname, '..', 'index.html'), 'utf8');

// ----------------------------------------------------------------------
// 1. Markup: headline, subtitle, CTA.
// ----------------------------------------------------------------------

test('empty-state card exists, starts hidden, and carries the "No Rawk Found" headline', () => {
  assert.match(
    INDEX_HTML,
    /<div[^>]*id="graph-empty-state"[^>]*hidden/,
    'Expected <div id="graph-empty-state" ... hidden> markup. It must start ' +
      'hidden so it only appears once syncSearchEmptyState() decides a search ' +
      'came back empty.'
  );
  // The headline copy is the project owner's phrasing — not a placeholder to
  // be "improved" into something generic like "No results found".
  assert.match(
    INDEX_HTML,
    /class="graph-empty-state__title">No Rawk Found</,
    'Expected the headline to read exactly "No Rawk Found" (backlog item #21, ' +
      'project owner\'s wording).'
  );
});

test('empty-state card asks the user whether they want to add the band, and echoes their query', () => {
  assert.match(
    INDEX_HTML,
    /class="graph-empty-state__sub">[\s\S]{0,200}Want to add them\?/,
    'Expected a subtitle inviting the user to add the band they searched for. ' +
      'Without the invitation the card is a dead end.'
  );
  assert.match(
    INDEX_HTML,
    /id="graph-empty-state-query"/,
    'Expected a #graph-empty-state-query span so the card can echo the search ' +
      'term back to the user. Confirming what we searched for is what makes ' +
      'the "add them?" offer legible.'
  );
});

test('empty-state card has a CTA button', () => {
  assert.match(
    INDEX_HTML,
    /<button[^>]*id="graph-empty-state-cta"[^>]*>/,
    'Expected a <button id="graph-empty-state-cta"> in the empty state. This ' +
      'is the only path from a failed search into the Add-band flow.'
  );
});

// ----------------------------------------------------------------------
// 2. It is an overlay, not SVG content.
// ----------------------------------------------------------------------

test('empty state is a DOM sibling of #graph-svg, not SVG content', () => {
  // #graph-svg must stay an empty element in the static markup — everything
  // inside it is generated by D3 and cleared on every render.
  assert.match(
    INDEX_HTML,
    /<svg id="graph-svg"[^>]*><\/svg>/,
    'Expected #graph-svg to remain empty in the static markup. If the empty ' +
      'state were nested inside it, graphGroup.selectAll("*").remove() would ' +
      'delete it on the next render.'
  );

  // Positive placement check: the card sits between the <svg> and the stats
  // badge, both of which are direct children of .graph-stage. That pins it
  // to the overlay layer without depending on brittle nesting regexes.
  const svgIndex = INDEX_HTML.indexOf('<svg id="graph-svg"');
  const emptyStateIndex = INDEX_HTML.indexOf('<div class="graph-empty-state" id="graph-empty-state"');
  const badgeIndex = INDEX_HTML.indexOf('<div class="graph-stats-badge" id="graph-stats-badge"');
  assert.ok(svgIndex > -1, 'Expected #graph-svg in index.html.');
  assert.ok(emptyStateIndex > -1, 'Expected the #graph-empty-state div in index.html.');
  assert.ok(badgeIndex > -1, 'Expected #graph-stats-badge in index.html.');
  assert.ok(
    svgIndex < emptyStateIndex && emptyStateIndex < badgeIndex,
    'Expected #graph-empty-state to sit between #graph-svg and ' +
      '#graph-stats-badge inside .graph-stage — i.e. in the same DOM overlay ' +
      'layer as the rest of the HUD, so its visibility is independent of what ' +
      'renderGraph() does to the SVG.'
  );
});

test('empty-state CSS positions it over the stage above the graph', () => {
  const ruleMatch = INDEX_HTML.match(/\.graph-empty-state\s*\{([^}]+)\}/);
  assert.ok(ruleMatch, 'Expected a .graph-empty-state CSS rule.');
  const rule = ruleMatch[1];
  assert.match(
    rule,
    /position:\s*absolute/,
    'The empty state must be position:absolute so it centers inside the ' +
      'position:relative .graph-stage.'
  );
  const zIndexMatch = rule.match(/z-index:\s*(\d+)/);
  assert.ok(zIndexMatch, 'Expected an explicit z-index on .graph-empty-state.');
  // .graph-stage is z-index 0 and #graph-badge is 9; the popovers are 15 and
  // the mobile sheet is 70. The card has to clear the graph without covering
  // the Add-band popover it opens.
  const zIndex = Number(zIndexMatch[1]);
  assert.ok(
    zIndex > 9 && zIndex < 15,
    `Expected .graph-empty-state z-index between 10 and 14 (got ${zIndex}). ` +
      'Below 10 it can be painted under the graph chrome; 15 or above and it ' +
      'covers the Add-band popover the CTA opens.'
  );
});

// ----------------------------------------------------------------------
// 3. Mobile parity.
// ----------------------------------------------------------------------

test('empty state renders on mobile too (not inside .graph-overlay-top, never display:none)', () => {
  // .graph-overlay-top is display:none under 900px. Anything the mobile user
  // needs cannot live inside it — that's the PR #42/#44 bug.
  const overlayTopIndex = INDEX_HTML.indexOf('<div class="graph-overlay graph-overlay-top">');
  const emptyStateIndex = INDEX_HTML.indexOf('<div class="graph-empty-state" id="graph-empty-state"');
  assert.ok(overlayTopIndex > -1, 'Expected .graph-overlay-top in index.html.');
  assert.ok(
    emptyStateIndex > overlayTopIndex,
    'Sanity check on markup order: the empty state should come after the ' +
      '.graph-overlay-top block, alongside the SVG.'
  );
  // The toolbar's own popovers close before </div> of .graph-overlay-top, and
  // the SVG (a stage-level sibling) sits between it and the empty state — so
  // if #graph-svg is between them, the empty state is outside the overlay.
  const svgIndex = INDEX_HTML.indexOf('<svg id="graph-svg"');
  assert.ok(
    overlayTopIndex < svgIndex && svgIndex < emptyStateIndex,
    'Expected #graph-svg to sit between .graph-overlay-top and ' +
      '#graph-empty-state, which proves the empty state is not nested inside ' +
      'the desktop-only overlay (display:none under 900px).'
  );

  // And no media query may hide it.
  assert.ok(
    !/@media[^{]*\{[^}]*\.graph-empty-state[^}]*display:\s*none/.test(INDEX_HTML),
    'No media query may set display:none on .graph-empty-state. The empty ' +
      'state must reach mobile visitors — they are the ones most likely to ' +
      'mistype a band name.'
  );
});

// ----------------------------------------------------------------------
// 4. Show / hide logic.
// ----------------------------------------------------------------------

test('syncSearchEmptyState shows the card only for a non-empty search with zero matches', () => {
  const fnMatch = INDEX_HTML.match(
    /function\s+syncSearchEmptyState\s*\(\s*matchCount\s*\)\s*\{([\s\S]*?)\n\s{4}\}/
  );
  assert.ok(fnMatch, 'Expected function syncSearchEmptyState(matchCount) in index.html.');
  const body = fnMatch[1];

  // Both conditions, ANDed. currentSearch alone would fire the card on a
  // successful search; matchCount alone would fire it when a scene/genre
  // filter empties the graph, where "add this band" is the wrong offer.
  assert.match(
    body,
    /Boolean\(currentSearch\)\s*&&\s*matchCount\s*===\s*0/,
    'The card must be gated on BOTH a non-empty currentSearch AND ' +
      'matchCount === 0. A zero-result filter combination must not offer to ' +
      'add a band — the band may be in the tree and merely filtered out.'
  );
  // Hiding is the same code path, so a search that starts matching (or is
  // cleared) puts the card away without a separate teardown call.
  assert.match(
    body,
    /graphEmptyState\.hidden\s*=\s*!show/,
    'syncSearchEmptyState must drive the hidden attribute from the same ' +
      '`show` boolean, so results appearing or the query being cleared ' +
      'dismisses the card automatically.'
  );
  assert.match(
    body,
    /graphEmptyStateQuery\.textContent\s*=/,
    'syncSearchEmptyState must write the current query into ' +
      '#graph-empty-state-query so the card echoes what was searched for.'
  );
});

test('renderGraph syncs the empty state BEFORE its empty-node-set early return', () => {
  const callIndex = INDEX_HTML.indexOf('syncSearchEmptyState(filtered.nodes.length)');
  // Matched on the condition alone, not `if (!nodes.length) return;`: the
  // guard is now a block that logs the filter combination before returning.
  const earlyReturnIndex = INDEX_HTML.indexOf('if (!nodes.length)');
  assert.ok(
    callIndex > -1,
    'Expected renderGraph() to call syncSearchEmptyState(filtered.nodes.length).'
  );
  assert.ok(earlyReturnIndex > -1, "Expected renderGraph()'s `if (!nodes.length)` early return.");
  assert.ok(
    callIndex < earlyReturnIndex,
    'syncSearchEmptyState() must be called BEFORE the `if (!nodes.length)` early ' +
      'return. That early return is exactly the zero-result case the empty state ' +
      'exists for — calling after it means the card never appears.'
  );
});

test('both the desktop and the mobile search input re-render the graph, so both sync the card', () => {
  // The empty state piggy-backs on renderGraph(), so parity comes for free
  // as long as both inputs still call it. If either stops, mobile or desktop
  // silently loses the card.
  assert.match(
    INDEX_HTML,
    /getElementById\('node-search'\)\.addEventListener\('input',\s*event\s*=>\s*\{[\s\S]{0,200}renderGraph\(\)/,
    'The desktop #node-search input handler must still call renderGraph().'
  );
  assert.match(
    INDEX_HTML,
    /mobileSearch\.addEventListener\('input',\s*ev\s*=>\s*\{[\s\S]{0,200}renderGraph\(\)/,
    'The #mobile-node-search input handler must still call renderGraph(). ' +
      'This is what gives the empty state mobile parity.'
  );
});

// ----------------------------------------------------------------------
// 5. CTA: existing signup gate + pre-fill.
// ----------------------------------------------------------------------

test('CTA opens the Add-band flow through the existing openSignupPopover funnel', () => {
  const fnMatch = INDEX_HTML.match(
    /function\s+openAddBandFromEmptyState\s*\(\s*\)\s*\{([\s\S]*?)\n\s{4}\}/
  );
  assert.ok(fnMatch, 'Expected function openAddBandFromEmptyState() in index.html.');
  const body = fnMatch[1];

  // One funnel for every "get me into the add/edit flow" affordance: the
  // welcome nudge CTA, the node-card sign-in hint, and now this. Signed-out
  // visitors get the sign-up gate inside #add-band-popover; signed-in
  // visitors get the form. Building a second gate here would drift.
  assert.match(
    body,
    /openSignupPopover\(\)/,
    'The empty-state CTA must call openSignupPopover(). For signed-out ' +
      'visitors that popover IS the sign-up gate, so this reuses the existing ' +
      'gate rather than adding a parallel one.'
  );
  // openSignupPopover() clicks the trigger, and that trigger toggles — so a
  // blind call would CLOSE an already-open popover.
  assert.match(
    body,
    /if\s*\(!popover\s*\|\|\s*popover\.hidden\)\s*openSignupPopover\(\)/,
    'openAddBandFromEmptyState must only call openSignupPopover() when ' +
      '#add-band-popover is closed. The Add-your-band trigger toggles, so ' +
      'clicking it while the popover is open would dismiss it.'
  );
  // Pre-fill only makes sense once the form is actually reachable.
  assert.match(
    body,
    /if\s*\(loadCurrentUser\(\)\)\s*prefillAddBandName\(currentSearch\)/,
    'Pre-fill must be gated on loadCurrentUser(). A signed-out visitor sees ' +
      'the sign-up gate, not the band form, so there is nothing to pre-fill yet.'
  );
});

test('CTA is wired to openAddBandFromEmptyState and stops the click from closing the popover', () => {
  assert.match(
    INDEX_HTML,
    /getElementById\('graph-empty-state-cta'\)\?\.addEventListener\('click',\s*event\s*=>\s*\{([\s\S]{0,400}?)\}\);/,
    'Expected a click listener bound to #graph-empty-state-cta.'
  );
  const handler = INDEX_HTML.match(
    /getElementById\('graph-empty-state-cta'\)\?\.addEventListener\('click',\s*event\s*=>\s*\{([\s\S]{0,400}?)\}\);/
  )[1];
  assert.match(
    handler,
    /event\.stopPropagation\(\)/,
    'The CTA handler must stopPropagation(). The document-level ' +
      '"click outside → close popovers" handler would otherwise dismiss the ' +
      'popover we just opened (same fix as the mobile Add-your-band trigger).'
  );
  assert.match(
    handler,
    /openAddBandFromEmptyState\(\)/,
    'The CTA handler must call openAddBandFromEmptyState().'
  );
});

test('pre-fill writes the search term into #band-name and lets the form revalidate', () => {
  const fnMatch = INDEX_HTML.match(
    /function\s+prefillAddBandName\s*\(\s*name\s*\)\s*\{([\s\S]*?)\n\s{4}\}/
  );
  assert.ok(fnMatch, 'Expected function prefillAddBandName(name) in index.html.');
  const body = fnMatch[1];
  assert.match(
    body,
    /getElementById\('band-name'\)/,
    'prefillAddBandName must target the existing #band-name input rather than ' +
      'introducing a new field.'
  );
  assert.match(body, /field\.value\s*=\s*name/, 'prefillAddBandName must set the field value.');
  // Setting .value programmatically fires no input event, so the form's
  // canonical-match / duplicate-band detection would never run on the
  // pre-filled name.
  assert.match(
    body,
    /dispatchEvent\(new Event\('input',\s*\{\s*bubbles:\s*true\s*\}\)\)/,
    "prefillAddBandName must dispatch an 'input' event so " +
      'validateSubmissionForm() runs its canonical-match and duplicate-band ' +
      'checks against the pre-filled name.'
  );
});

// ----------------------------------------------------------------------
// 6. Cleanup: stale copy + the redundant second empty-state surface.
// ----------------------------------------------------------------------

test('stale "from your uploaded CSV" copy is gone', () => {
  // The graph is Neon-backed (/api/bands); the CSV is only a local
  // last-resort fallback. Telling users their data came from "your uploaded
  // CSV" was wrong on every real page load.
  assert.ok(
    !INDEX_HTML.includes('from your uploaded CSV'),
    'Expected the "from your uploaded CSV" copy to be gone. The data model is ' +
      'Neon-backed; nothing the user sees comes from an upload they performed.'
  );
});

test('the redundant #graph-note-* empty-state surface is gone', () => {
  // .graph-shell-footer was display:none !important globally (full-screen
  // stage pass), so #graph-note-left's "No matches yet." text had been
  // unreachable — a second, invisible empty-state surface competing with
  // #graph-badge. Consolidated away in favor of #graph-empty-state.
  assert.ok(
    !INDEX_HTML.includes('id="graph-note-left"'),
    'Expected #graph-note-left to be removed. It lived inside the globally ' +
      'display:none .graph-shell-footer, so its empty-state copy was dead ' +
      'weight competing with #graph-badge.'
  );
  assert.ok(
    !INDEX_HTML.includes('id="graph-note-right"'),
    'Expected #graph-note-right to be removed along with the footer it lived in.'
  );
  assert.ok(
    !/\bnoteLeft\b/.test(INDEX_HTML) && !/\bnoteRight\b/.test(INDEX_HTML),
    'Expected the noteLeft / noteRight variables and every write to them to be ' +
      'gone. Leaving them behind is a guaranteed null-deref once the spans are ' +
      'removed from the DOM.'
  );
  assert.ok(
    !/class="graph-shell-footer"/.test(INDEX_HTML),
    'Expected the .graph-shell-footer wrapper markup to be removed.'
  );
  // Dead selectors for a removed element are the same smell the
  // node-card__edit-btn cleanup called out.
  assert.ok(
    !/^\s*\.graph-shell-footer\s*[,{]/m.test(INDEX_HTML) && !/^\s*\.graph-note\s*\{/m.test(INDEX_HTML),
    'Expected the .graph-shell-footer / .graph-note CSS rules to be removed ' +
      'along with the markup they styled.'
  );
});

test('#graph-badge survives as the active-filter readout, distinct from the empty state', () => {
  // The two surfaces are NOT redundant with each other and both stay:
  //   #graph-badge      — which filters are currently applied.
  //   #graph-empty-state — the search came back with nothing.
  // A user can see "Search: heart · Grunge" in the badge while the card
  // explains that the combination matched nothing.
  assert.match(
    INDEX_HTML,
    /id="graph-badge"/,
    'Expected #graph-badge to still exist. It reports which filters are ' +
      'active, which is orthogonal to whether the result set is empty.'
  );
  assert.match(
    INDEX_HTML,
    /graphBadge\.textContent\s*=\s*badgeParts\.length\s*\?\s*badgeParts\.join\(' · '\)\s*:\s*'Full graph'/,
    'Expected #graph-badge to keep summarising the active filters ' +
      '("Full graph" when none). The empty state must not take this over.'
  );
});
